site_name: Jean-Luc Tibaux (@eUgEntOptIc44)
site_url: https://eugentoptic44.codeberg.page
repo_url: https://gitlab.com/eUgEntOptIc44/eUgEntOptIc44.gitlab.io
edit_uri: ""

nav:
    - Projects: index.md
    - Snippets: snippets.md

theme:
  name: material
  fonts: false
  features:
   - navigation.instant
   - navigation.tabs
   - navigation.tracking
   - navigation.sections
   - navigation.indexes
   - navigation.top
   - toc.integrate
  palette:
   - media: "(prefers-color-scheme: light)"
     scheme: default
     accent: teal
     primary: blue
     toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: slate
     primary: blue
     accent: teal
     toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: overrides
  icon:
     repo: fontawesome/brands/gitlab
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png

plugins:
   - search:
      lang:
        - en
        - de
   - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
   - git-revision-date-localized:
      type: datetime
      locale: en # remove this when using i18n plugin for translations
      enable_creation_date: true

markdown_extensions:
   - toc:
      toc_depth: 3
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
   - abbr
   - admonition
   - attr_list
   - pymdownx.highlight
   - pymdownx.superfences
   - pymdownx.tabbed
   - footnotes
   - pymdownx.critic
   - pymdownx.betterem:
      smart_enable: all
   - pymdownx.caret
   - pymdownx.mark
   - pymdownx.tilde
   - pymdownx.smartsymbols
   - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
       custom_icons:
        - overrides/.icons
   - pymdownx.details
   - pymdownx.arithmatex: # preserve LaTex code -> requires including MathJax -> https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
      generic: true
   - pymdownx.tasklist: # needs extra css -> https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
      custom_checkbox: true
   - pymdownx.magiclink # recognize links in plaintext
   - pymdownx.keys # to display keyboard keys
   - pymdownx.progressbar # needs extra css -> https://facelessuser.github.io/pymdown-extensions/extensions/progressbar/
   - pymdownx.escapeall # escape ALL non standard chars -> https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/
   - meta
   - def_list

copyright: Copyright &copy; 2021 Jean-Luc Tibaux
